core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    forgot_password,
    login_admin,
    login_buyer,
    login_seller,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    add_coupon,
    add_new_item,
    AddNewItemView,
    reset_password,
    signup_buyer,
    signup_seller,
    verify_buyer,
    verify_seller,
    model_form_upload,
    ViewDocument,
    decline_request,
    accept_request,
    ViewSellerProfile,
    SellerHome,
    siteadmin,
    deleteproduct,
    login_admin,
    adminhome,
    get_category_products,
    rate_limit,
    reset_password
)


app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', add_coupon, name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    # path('add-new-item/', add_new_item, name='add-new-item')
    path('add-new-item/', AddNewItemView.as_view(), name='add-new-item'),
    path("login_buyer/",login_buyer, name='login_buyer'),
    path("signup_buyer/", signup_buyer, name='signup_buyer'),
    path("otp-buyer/<auth_token>/", verify_buyer, name="verify_buyer"),
    path("login_seller/",login_seller, name='login_seller'),
    path("signup_seller/", signup_seller, name='signup_seller'),
    path("otp-seller/<auth_token>/", verify_seller, name="verify_seller"),
    path('uploadfile/', model_form_upload, name='uploadfile'),
    path('viewfiles/', ViewDocument, name='viewfiles'),
    path('viewfiles/decline/<id>',decline_request, name='decline_request'),
    path('viewfiles/accept/<id>',accept_request, name='accept_request'),
    path('viewseller/',ViewSellerProfile, name='viewseller'),
    path('sellerhome/',SellerHome, name='sellerhome'),
    path("siteadmin/", siteadmin, name="siteadmin"),
    path("deleteproduct/", deleteproduct, name="deleteproduct"),
    path("login_admin/", login_admin, name="login_admin"),
    path("adminhome/", adminhome, name="adminhome"),
    path("home/<category>", get_category_products, name="get_category_products"),
    path("ratelimit/", rate_limit, name="ratelimit"),
    path("forgot_password/", forgot_password, name="forgot_password"),
    path("reset_password/", reset_password, name="reset_password"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATICFILES_DIRS}),
]


# if settings.DEBUG:
#     urlpatterns += patterns('',
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#    )

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.db.models import Sum 
from django_countries.fields import CountryField
from django.contrib.auth.models import User


CATEGORY_CHOICES = (
    ('S', 'Clothes'),
    ('SW', 'Electronics'),
    ('OW', 'Stationery')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    image2 = models.ImageField(blank=True, null=True)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        }) 

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        }) 
    
    def category_url_clothes(self):
        return reverse("core:home") + '/S'
    
    def category_url_electronics(self):
        return reverse("core:home") + '/SW'
    
    def category_url_stationery(self):
        return reverse("core:home") + '/O'

        
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100,null=True)
    apartment_address = models.CharField(max_length=100,null=True)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    
    def __str__(self):
        return self.code


class Buyer(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    otp_done = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Seller(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)
    otp_done = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
class SellerItem(models.Model):
    user=models.ForeignKey(Seller, on_delete=models.CASCADE)
    item=models.ForeignKey(Item, on_delete=models.CASCADE)


class SiteAdmin(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    
    
    def get_decline_url(self):
        return reverse("core:viewfiles")+'decline/'+str(self.id)


    def get_accept_url(self):
        return reverse("core:viewfiles")+'accept/'+str(self.id)

templates/adminhome.html
<!DOCTYPE >
<html>
<head>
    {% load static %}
    {% load cart_template_tags %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            /* background-color: #52ab98; */
            display: grid;
            place-items: center;
            min-height: 100vh;
        }
        .seller-home-container {
            width: 1000px;
            background-color: #ffffff;
            position: relative;
            display: grid;
            grid-template-columns: 52% 48%;
            align-items: center;
            font-family: 'Quicksand', sans-serif;
            margin-top:35px;
            margin-bottom: 50px;
            padding-top: 50px;
        }
        #seller-home-img {
            width: 90%;
            height: auto;
        }
        #welcome {
            font-size: 26px;
            font-weight: bold;
            color: #2b6777;
            margin-bottom: 10px;
        }
        .page-text {
            margin: 20px 0 20px 0;
            padding: 20px;
            border-radius: 15px;
            box-shadow: rgba(50, 50, 93, 0.25) 0px 6px 12px -2px, rgba(0, 0, 0, 0.3) 0px 3px 7px -3px;
        }
        .page-text:nth-child(odd) {
            background-color: whitesmoke;
        }
        .page-text:hover {
            box-shadow: rgba(0, 0, 0, 0.15) 2.4px 2.4px 3.2px;
        }
        #add-new-item, #view-my-profile, #get-verified {
            color: rgba(0, 0, 255, 0.589);
            font-weight: bold;
        }
        #add-new-item:hover, #view-my-profile:hover, #get-verified:hover {
            color: rgba(7, 7, 133, 0.774);
        }
        
        footer {
            width: 100%;
        }
    </style>
</head>
<body>
    <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% csrf_token %}
    
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">
            
            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="#">
                <img src="{% static 'img/logo.png' %}" style="width:35px; height:35px">
                <!-- <strong class="blue-text">FCS e-Commerce</strong> -->
            </a>
            
            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <!-- Left -->
            <ul class="navbar-nav mr-auto">
            </ul>
            
            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                        <span class="clearfix d-none d-sm-inline-block">Logout</span>
                    </a>
                </li>                                 
                {% endif %}
            </ul>
        </div>
    </nav>
    
    
    <div class="seller-home-container">
        
        <img id="seller-home-img" src="{% static 'img/login2.jpg' %}">
        <div class="container-text">
            <p id="welcome">Welcome, Site Admin!</p>
            <div class="page-text">
                <p>You can delete sellers or buyers.</p>
                <p><a id="get-verified" href="{% url 'core:siteadmin' %}">Delete Users</a></p>
            </div>
            <div class="page-text">
                <p>You can delete products.</p>
                <p><a id="add-new-item" href="{% url 'core:deleteproduct' %}">Delete Products</a></p>
            </div>
            <div class="page-text">
                <p>You can verify sellers.</p>
                <p><a id="view-my-profile"  href="{% url 'core:viewfiles' %}">Review Sellers</a></p> 
            </div>   
        </div>
        
    </div>
    
    
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
        <hr class="my-4">
        <div class="pb-4">
            <a href=""><i class="fab fa-facebook-f mr-3"></i></a>
            <a href=""><i class="fab fa-twitter mr-3"></i></a>
            <a href="https://youtu.be/dQw4w9WgXcQ" target="_blank"><i class="fab fa-youtube mr-3"></i></a>
            <a href="https://www.instagram.com/p/CWCHjt2BSwH/?utm_source=ig_web_copy_link" target="_blank"><i class="fab fa-instagram mr-3"></i></a>
        </div>
        <div class="footer-copyright py-3">
            <a href="#"><strong>G17</strong></a>
            <p style="font-size:11px">Vector Art from: <a href="https://www.vecteezy.com" style="font-size:11px">vecteezy.com</a></p>
        </div>
    
    </footer>
    
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
    </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}
    
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>

</html>

templates/login_buyer.html
{% extends "base.html"%}
{% load static %}
{% load cart_template_tags %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/keyboard.css' %}">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block content %}

<style>
    /* @import url('https://fonts.googleapis.com/css2?family=Quicksand&display=swap'); */
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    body {
        display: grid;
        place-items: center;
        min-height: 100vh;
    }
    .global-container {
        font-family: 'Quicksand', sans-serif;
        width: 900px;
        background-color: #ffffff;
        position: relative;
        display: grid;
        grid-template-columns: 54% 46%;
        border-radius: 20px;
        box-shadow: 0 15px 20px rgba(0, 0, 0, 0.356);
        align-items: center;
        /* font-family: 'Quicksand', sans-serif; */
        margin-top: 60px;
        margin-bottom: 50px;
        padding: 40px 20px 40px 20px;
    }
    #my-profile-img {
        width: 88%;
        height: auto;
    }
    .container-text {
        margin-right: 40px;
    }
    label, input {
        font-size: 14px;
    }
    footer {
        width: 100%;
    }
</style>

<script type="text/javascript" src="{% static 'js/keyboard.js' %}"></script>            
<div class="global-container">
    <img id="my-profile-img" src="{% static 'img/login2.jpg' %}">
    <div class="container-text">
        <h3 class="card-title text-center">Log In As A Buyer</h3><hr>
        <div class="card-text">
            
            <form method="post" >
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" name="username" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <a href="#" style="float:right;font-size:12px;margin-bottom:5px">Forgot password?</a>
                    <input type="password" name="password" class="form-control form-control-sm" id="exampleInputPassword1">
                </div>
                <button type="submit" class="btn btn-primary btn-block" style="width:50%;">Sign in</button>
                
                <div class="sign-up" style="font-size: 12px;margin-top:8px">
                    Don't have an account? <a href="{% url 'core:signup_buyer' %}">Create One</a>
                </div>
            </form>
        </div>
    </div>
</div>
</div>


{% endblock %}

templates/login_seller.html
{% extends "base.html"%}
{% load static %}
{% load cart_template_tags %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/keyboard.css' %}">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block content %}

<style>
    /* @import url('https://fonts.googleapis.com/css2?family=Quicksand&display=swap'); */
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    body {
        display: grid;
        place-items: center;
        min-height: 100vh;
    }
    .global-container {
        font-family: 'Quicksand', sans-serif;
        width: 900px;
        background-color: #ffffff;
        position: relative;
        display: grid;
        grid-template-columns: 54% 46%;
        border-radius: 20px;
        box-shadow: 0 15px 20px rgba(0, 0, 0, 0.356);
        align-items: center;
        /* font-family: 'Quicksand', sans-serif; */
        margin-top: 60px;
        margin-bottom: 50px;
        padding: 40px 20px 40px 20px;
    }
    #my-profile-img {
        width: 88%;
        height: auto;
    }
    .container-text {
        margin-right: 40px;
    }
    label, input {
        font-size: 14px;
    }
    footer {
        width: 100%;
    }
</style>

<script type="text/javascript" src="{% static 'js/keyboard.js' %}"></script>  


<div class="global-container">
    <img id="my-profile-img" src="{% static 'img/login1.jpg' %}">
    <div class="container-text">
        <h3 class="card-title text-center">Log In As A Seller</h3><hr>
        <div class="card-text">
            
            <form method="post" >
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" name="username" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <a href="{% url 'core:forgot_password' %}" style="float:right;font-size:12px;">Forgot password?</a>
                    <input type="password" name="password" class="form-control form-control-sm" id="exampleInputPassword1">
                </div>
                <button type="submit" class="btn btn-primary btn-block" style="width:50%;">Sign in</button>
                
                <div class="sign-up" style="font-size: 12px;margin-top:10px;">
                    Don't have an account? <a href="{% url 'core:signup_seller' %}">Create One</a>
                </div>
            </form>
        </div> 
    </div>
</div>


{% endblock %}

templates/sellerhome.html
<!DOCTYPE >
<html>
<head>
    {% load static %}
    {% load cart_template_tags %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            display: grid;
            place-items: center;
            min-height: 100vh;
        }
        .seller-home-container {
            width: 1000px;
            background-color: #ffffff;
            position: relative;
            display: grid;
            grid-template-columns: 52% 48%;
            align-items: center;
            font-family: 'Quicksand', sans-serif;
            margin-top:35px;
            margin-bottom: 50px;
            padding-top: 50px;
        }
        #seller-home-img {
            width: 90%;
            height: auto;
        }
        #welcome {
            font-size: 26px;
            font-weight: bold;
            color: #2b6777;
            margin-bottom: 10px;
        }
        .page-text {
            margin: 20px 0 20px 0;
            padding: 20px;
            border-radius: 15px;
            box-shadow: rgba(50, 50, 93, 0.25) 0px 6px 12px -2px, rgba(0, 0, 0, 0.3) 0px 3px 7px -3px;
        }
        .page-text:nth-child(odd) {
            background-color: whitesmoke;
        }
        .page-text:hover {
            box-shadow: rgba(0, 0, 0, 0.15) 2.4px 2.4px 3.2px;
        }
        #add-new-item, #view-my-profile, #get-verified {
            color: rgba(0, 0, 255, 0.589);
            font-weight: bold;
        }
        #add-new-item:hover, #view-my-profile:hover, #get-verified:hover {
            color: rgba(7, 7, 133, 0.774);
        }
        
        footer {
            width: 100%;
        }
    </style>
</head>
<body>
    <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% csrf_token %}
    
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">
            
            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="#">
                <img src="{% static 'img/logo.png' %}" style="width:35px; height:35px">
            </a>
            
            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <!-- Left -->
            <ul class="navbar-nav mr-auto">
            </ul>
            
            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                        <span class="clearfix d-none d-sm-inline-block">Logout</span>
                    </a>
                </li> 
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'core:viewseller' %}">
                        <span class="clearfix d-none d-sm-inline-block" style="font-weight:bold; color:#2b6777;">{{request.user.username}}</span>
                    </a>
                </li>
                                             
                {% endif %}
            </ul>
        </div>
    </nav>
    
    
    <div class="seller-home-container">
        
        <img id="seller-home-img" src="{% static 'img/seller-home-page.jpg' %}">
        <div class="container-text">
            <p id="welcome">Welcome, {{request.user.username}}!</p>
            <div class="page-text">
                <p>To start selling your products, you need to be verified.</p>
                <p><a id="get-verified" href="{% url 'core:uploadfile' %}">Get Verified</a></p>
            </div>
            <div class="page-text">
                <p>Once verified, you can start adding your products to our website.</p>
                <p><a id="add-new-item" href="{% url 'core:add-new-item' %}">Add New Item</a></p>
            </div>
            <div class="page-text">
                <p>You can also view your profile.</p>
                <p><a id="view-my-profile"  href="{% url 'core:viewseller' %}">My Profile</a></p> 
            </div>   
        </div>
        
    </div>
    
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
        <hr class="my-4">
        <div class="pb-4">
            <a href=""><i class="fab fa-facebook-f mr-3"></i></a>
            <a href=""><i class="fab fa-twitter mr-3"></i></a>
            <a href="https://youtu.be/dQw4w9WgXcQ" target="_blank"><i class="fab fa-youtube mr-3"></i></a>
            <a href="https://www.instagram.com/p/CWCHjt2BSwH/?utm_source=ig_web_copy_link" target="_blank"><i class="fab fa-instagram mr-3"></i></a>
        </div>
        <div class="footer-copyright py-3">
            <a href="#"><strong>G17</strong></a>
            <p style="font-size:11px">Vector Art from: <a href="https://www.vecteezy.com" style="font-size:11px">vecteezy.com</a></p>
        </div>
    </footer>
    
</body>
</html>